version: '3.8'

services:
  mongodb:
    image: mongo:5.0.9
    container_name: mongodb_groupr
    volumes:
      # Named volume to persist database
      - groupr_data:/data/db
    env_file:
      - ./.env
    ports:
      - '27017:27017'

volumes:
  groupr_data:
